running training script
[I 2024-12-17 16:35:37,842] A new study created in RDB with name: no-name-5c78c7a3-ac1d-400e-90b2-f0663af696b9
training using optuna
model type is mdx23c
Instruments: ['vocals', 'bass', 'drums', 'other']
Metrics for training: ['sdr']. Metric for scheduler: sdr
Use augmentation for training
Dataset type: 1 Processes to use: 8 
Collecting metadata for ['../data/MUSDB18HQ/train']
  0%|          | 0/80 [00:00<?, ?it/s]  1%|▏         | 1/80 [00:09<13:07,  9.96s/it] 22%|██▎       | 18/80 [00:10<00:24,  2.50it/s] 35%|███▌      | 28/80 [00:10<00:11,  4.42it/s] 52%|█████▎    | 42/80 [00:10<00:04,  8.09it/s] 71%|███████▏  | 57/80 [00:10<00:01, 13.40it/s] 91%|█████████▏| 73/80 [00:10<00:00, 20.76it/s]100%|██████████| 80/80 [00:10<00:00,  7.59it/s]
Found tracks in dataset: 80
CUDA is not available. Training on CPU will be very slow...
Patience: 2 Reduce factor: 0.8646169769190775 Batch size: 4 Grad accum steps: 4 Effective batch size: 16 Optimizer: adam
Train for: 5
Train epoch: 0 Learning rate: 2.47448010859993e-05
  0%|          | 0/100 [00:00<?, ?it/s]Running command: python train_optuna.py --model_type mdx23c --config_path configs/config_musdb18_mdx23c.yaml --results_path checkpoints/mdx23c_2024-12-17_16-35-32 --data_path ../data/MUSDB18HQ/train --valid_path ../MUSDB18HQ/validation --num_workers 4 --start_check_point  --device_ids 0
Traceback (most recent call last):
  File "/Users/kaimikkelsen/canada_compute/Music-Source-Separation-Training/run_training.py", line 45, in <module>
    main()
  File "/Users/kaimikkelsen/canada_compute/Music-Source-Separation-Training/run_training.py", line 39, in main
    subprocess.run(command, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1141, in communicate
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1938, in _wait
    (pid, sts) = self._try_wait(0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1896, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
Exception ignored in atexit callback: <bound method TemporaryDirectory.cleanup of <TemporaryDirectory '/var/folders/nn/xmq_vw3n7kzb3fr1ylfyz3t80000gn/T/tmpw8w5nrc9wandb-media'>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py", line 846, in cleanup
Process Process-11:
Exception ignored in atexit callback: <bound method Sentry.end_session of <wandb.analytics.sentry.Sentry object at 0x109b08cd0>>
Traceback (most recent call last):
  File "/Users/kaimikkelsen/canada_compute/Music-Source-Separation-Training/test_env/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 46, in wrapper
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Process Process-14:
Process Process-10:
Process Process-16:
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py", line 799, in _rmtree
    @classmethod
KeyboardInterrupt: 
Process Process-15:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    return func(self, *args, **kwargs)
  File "/Users/kaimikkelsen/canada_compute/Music-Source-Separation-Training/test_env/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 179, in end_session
    client = self.scope.get_client()
  File "/Users/kaimikkelsen/canada_compute/Music-Source-Separation-Training/test_env/lib/python3.10/site-packages/sentry_sdk/scope.py", line 375, in get_client
    @classmethod
KeyboardInterrupt: 
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 333, in _bootstrap
    threading._shutdown()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1520, in _shutdown
    _main_thread._stop()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1043, in _stop
    if not self.daemon:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1163, in daemon
    @property
KeyboardInterrupt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 201, in _finalize_join
    thread.join()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1089, in join
    self._wait_for_tstate_lock()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1107, in _wait_for_tstate_lock
    self._stop()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1021, in _stop
    def _stop(self):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 201, in _finalize_join
    thread.join()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1081, in join
    if not self._initialized:
KeyboardInterrupt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 201, in _finalize_join
    thread.join()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1057, in join
    def join(self, timeout=None):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 201, in _finalize_join
    thread.join()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1089, in join
    self._wait_for_tstate_lock()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1103, in _wait_for_tstate_lock
    if lock is None:  # already determined that the C code is done
KeyboardInterrupt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 201, in _finalize_join
    thread.join()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1081, in join
    if not self._initialized:
KeyboardInterrupt
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 41 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
